os: osx

language: c

before_install:
  - brew update
  - brew install ninja
  - plex/scripts/build_osx_depends.sh osx64

script: 
  - mkdir ../pht-ninja-build
  - cd ../pht-ninja-build
  - cmake -GNinja -DCMAKE_INSTALL_PREFIX=/usr/local/PlexHomeTheater -DCOMPRESS_TEXTURES=off -DCREATE_BUNDLE=off -DENABLE_DUMP_SYMBOLS=off ../plex-home-theater-public
  - ninja install

notifications:
  email:
    recipients:
      - deng.tulin@icloud.com
    on_success: never # default: change
    on_failure: always # default: always
 
